### ISSUE TITLE
filetypesman@1.83: hash check failed

### ISSUE THREAD

**Issue by scorpion-t** [kodybrown/scoop-nirsoft#10]
Checking hash of filetypesman-x64.zip ... ERROR Hash check failed!
App:         nirsoft/filetypesman
URL:         http://www.nirsoft.net/utils/filetypesman-x64.zip
First bytes: 50 4B 03 04 14 00 02 00
Expected:    a92b316f3b14ace527df18fd39f9dee3af6153a758d4301df54718a9eb07a605
Actual:      5f422bc4aec8f5af962ac7c9c8d540f2198b330d454559f639673a9e4e1e9e7f

**Comment by kodybrown** [comment]
I updated binary and hash. Thank you for creating an issue!
