### ISSUE TITLE
shellexview@1.97: hash check failed

### ISSUE THREAD

**Issue by tronics22** [kodybrown/scoop-nirsoft#11]
scoop install shellexview shellmenuview sysexporter Terminus-NF
Installing 'shellexview' (1.97) [64bit]
shexview-x64.zip (101,5 KB) [=======================================================================================================================================================] 100%
Checking hash of shexview-x64.zip ... ERROR Hash check failed!
App:         nirsoft/shellexview
URL:         http://www.nirsoft.net/utils/shexview-x64.zip
First bytes: 50 4B 03 04 14 00 02 00
Expected:    a7116d5b8e66fe00fc076ec972832e643f8ba72457d54bb79cba07f9b9745c86
Actual:      73248fb48ee6387cadbd6bdde5265cbef465cea7fca8f3b72eac5c408f4e7ccb

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/kodybrown/scoop-nirsoft/issues/new?title=shellexview%401.97%3a+hash+check+failed

Thank you very much in advance,
Werner

**Comment by kodybrown** [comment]
I updated binary and hash. Thank you for creating an issue!
