### ISSUE TITLE
shellmenuview@1.40: hash check failed

### ISSUE THREAD

**Issue by tronics22** [kodybrown/scoop-nirsoft#12]
scoop install shellmenuview
Installing 'shellmenuview' (1.40) [64bit]
shmnview-x64.zip (65,9 KB) [========================================================================================================================================================] 100%
Checking hash of shmnview-x64.zip ... ERROR Hash check failed!
App:         nirsoft/shellmenuview
URL:         http://www.nirsoft.net/utils/shmnview-x64.zip
First bytes: 50 4B 03 04 14 00 02 00
Expected:    5227288fe979a10035ef5f8a03575a9856754182f78d9a94abcfe7608f76258e
Actual:      e5a5b7c4a6ce2772782243027c73974d9699f2ba1d3eab1f53bcff4096635b83

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/kodybrown/scoop-nirsoft/issues/new?title=shellmenuview%401.40%3a+hash+check+failed

Thank you very much in advance,
Werner

**Comment by kodybrown** [comment]
I updated binary and hash. Thank you for creating an issue!
