### ISSUE TITLE
usbdeview@3.02: hash check failed

### ISSUE THREAD

**Issue by rbeesley** [kodybrown/scoop-nirsoft#124]
  ~    scoop install usbdeview
WARN  Purging previous failed installation of usbdeview.
Uninstalling 'usbdeview' ().
'usbdeview' was uninstalled.
Installing 'usbdeview' (3.02) [64bit]
Loading usbdeview-x64.zip from cache
Checking hash of usbdeview-x64.zip ... ok.
usb.ids (699.3 KB) [==========================================================================================] 100%
Checking hash of usb.ids ... ERROR Hash check failed!
App:         nirsoft/usbdeview
URL:         http://www.linux-usb.org/usb.ids
First bytes: 23 0A 23 09 4C 69 73 74
Expected:    0ee5cca771c1ad9b02e6d271f37500155b2b957faab403014013487ba87c5798
Actual:      000244529760559849fac7a7e1984b17da21c0588aa91302599df9bff5bdce6f

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/kodybrown/scoop-nirsoft/issues/new?title=usbdeview%403.02%3a+hash+check+failed
  ~   

**Comment by kodybrown** [comment]
updated via https://github.com/kodybrown/scoop-nirsoft/commit/41220d981eddda0a449194068cbfc2c47ef23f8f
