### ISSUE TITLE
[Request] WinExplorer

### ISSUE THREAD

**Issue by he3als** [kodybrown/scoop-nirsoft#127]
# Description
It would be great if WinExplorer was added to this repository. WinExplorer is a utility that shows all system's windows in hierarchical display. For every window in the hierarchy, you can view its properties, like handle, class name, caption, size, position and more. You can also modify some properties, like Caption and Visible/Enabled.

### Image
![image](https://user-images.githubusercontent.com/65787561/162018423-b9d470c2-0d25-47d4-b980-5bb36a2f50df.png)

### Link
**Download:** https://www.nirsoft.net/utils/winexp.html

**Comment by kodybrown** [comment]
added
