### ISSUE TITLE
devmanview@1.75: hash check failed

### ISSUE THREAD

**Issue by mrchang2017** [kodybrown/scoop-nirsoft#128]
ERROR Hash check failed!
    App:         nirsoft/devmanview
    URL:         https://www.nirsoft.net/utils/devmanview-x64.zip
    First bytes: 50 4B 03 04 14 00 02 00
    Expected:    fb4eff5b3730a4014aa4406f4ad49a658761a8ebff43b6613bfcd3cd739768d1
    Actual:      a7dd51ea5ab57fe2f686fbb8dc0d5e96207d77d317da9e83c636f98bda4c5a4c

    Please try again or create a new issue by using the following link and paste your console output:
    https://github.com/kodybrown/scoop-nirsoft/issues/new?title=devmanview%401.75%3a+hash+check+failed

**Comment by kodybrown** [comment]
Fixed [here](https://github.com/kodybrown/scoop-nirsoft/commit/c09f15e6fea295c94707dad1798475b283c3eca9). Thanks!
