### ISSUE TITLE
wifiinfoview@2.75: hash check failed

### ISSUE THREAD

**Issue by wyattjee** [kodybrown/scoop-nirsoft#131]
Checking hash of wifiinfoview-x64.zip ... ERROR Hash check failed!
App:         nirsoft/wifiinfoview
URL:         https://www.nirsoft.net/utils/wifiinfoview-x64.zip
First bytes: 50 4B 03 04 14 00 02 00
Expected:    8ed79bb23baa275e42887f185755d21890d7dfd3134f5e21624d0cedac0e0fc7
Actual:      3febc8004e3f98fdbe10509472e25bb5396bbd53b3cb64bc607db90cb5da1fe7

**Comment by kodybrown** [comment]
Fixed [here](https://github.com/kodybrown/scoop-nirsoft/commit/c09f15e6fea295c94707dad1798475b283c3eca9). Thanks!
