### ISSUE TITLE
wifiinfoview@2.75: hash check failed

### ISSUE THREAD

**Issue by ntcarver0** [kodybrown/scoop-nirsoft#133]
Powershell output follows:

`` PowerShell 7.2.2
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

Warning: PowerShell detected that you might be using a screen reader and has disabled PSReadLine for compatibility purposes. If you want to re-enable it, run 'Import-Module PSReadLine'.

PS C:\Users\noahc> scoop install wifiinfoview
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
WARN  To disable this warning, run 'scoop config aria2-warning-enabled false'.
Installing 'wifiinfoview' (2.75) [64bit]
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: afb34f|OK  |   1.4MiB/s|C:/Users/noahc/scoop/cache/wifiinfoview#2.75#https_www.nirsoft.net_utils_wifiinfoview-x64.zip
Download: Status Legend:
Download: (OK):download completed.
Checking hash of wifiinfoview-x64.zip ... ERROR Hash check failed!
App:         nirsoft/wifiinfoview
URL:         https://www.nirsoft.net/utils/wifiinfoview-x64.zip
First bytes: 50 4B 03 04 14 00 02 00
Expected:    8ed79bb23baa275e42887f185755d21890d7dfd3134f5e21624d0cedac0e0fc7
Actual:      3febc8004e3f98fdbe10509472e25bb5396bbd53b3cb64bc607db90cb5da1fe7

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/kodybrown/scoop-nirsoft/issues/new?title=wifiinfoview%402.75%3a+hash+check+failed
PS C:\Users\noahc>

**Comment by kodybrown** [comment]
Fixed [here](https://github.com/kodybrown/scoop-nirsoft/commit/c09f15e6fea295c94707dad1798475b283c3eca9). Thanks!
