### ISSUE TITLE
simplewmiview@1.48: hash check failed

### ISSUE THREAD

**Issue by marvinlehmann** [kodybrown/scoop-nirsoft#138]
App:         nirsoft/simplewmiview
URL:         https://www.nirsoft.net/utils/simplewmiview-x64.zip
First bytes: 50 4B 03 04 14 00 02 00
Expected:    c10ab8346dbce14ddf7095d1135351aa0f5a610c63cd1fb33221b9df91331992
Actual:      9f0956ee19cf384d3ba43960ab7375219da63742fad9b124d87554dc87999b95

**Comment by kodybrown** [comment]
Fixed [here](https://github.com/kodybrown/scoop-nirsoft/commit/c09f15e6fea295c94707dad1798475b283c3eca9). Thanks!
