### ISSUE TITLE
usbdeview@3.02: hash check failed

### ISSUE THREAD

**Issue by secretfork** [kodybrown/scoop-nirsoft#144]
`Installing 'usbdeview' (3.02) [64bit]
usbdeview-x64.zip (122.4 KB) [================================================================================] 100%
Checking hash of usbdeview-x64.zip ... ERROR Hash check failed!
App:         nirsoft/usbdeview
URL:         https://www.nirsoft.net/utils/usbdeview-x64.zip
First bytes: 50 4B 03 04 14 00 02 00
Expected:    1802eccdc6eed1f1b5b50c59344677394c1b4a0590fe34450909ad13e3823cdd
Actual:      0ed3fae58c46d70e5b8c1988c8780e5de4310b80e23404669b8bb993d587be48

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/kodybrown/scoop-nirsoft/issues/new?title=usbdeview%403.02%3a+hash+check+failed`

**Comment by kodybrown** [comment]
Fixed [here](https://github.com/kodybrown/scoop-nirsoft/commit/c09f15e6fea295c94707dad1798475b283c3eca9)
