### ISSUE TITLE
soundvolumeview@2.30: hash check failed

### ISSUE THREAD

**Issue by pstaszko** [kodybrown/scoop-nirsoft#152]
App:         nirsoft/soundvolumeview
URL:         https://www.nirsoft.net/utils/soundvolumeview-x64.zip
First bytes: 50 4B 03 04 14 00 02 00
Expected:    11bbb1948819e8f2c79421f7743f13870fcd724d28c96b60e5f5400c6f975035
Actual:      4db156138ba3f474da294cf685c841fe70e6215c390b59ace8409beb13a00242

**Comment by metalgear8019** [comment]
Experiencing the same problem right now :(

**Comment by kodybrown** [comment]
Thanks for taking the time to create this issue!
Though, I'm sorry for such an absence!
_(I haven't been getting any notifications from GitHub since last August apparently.)_
I've updated all the apps.
