### ISSUE TITLE
searchmyfiles@3.17: hash check failed

### ISSUE THREAD

**Issue by laquazi** [kodybrown/scoop-nirsoft#153]
App:         nirsoft/searchmyfiles
URL:         https://www.nirsoft.net/utils/searchmyfiles-x64.zip
First bytes: 50 4B 03 04 14 00 02 00
Expected:    acebecb9079c79517b2c45678e7b14f212c40d37592a58bfd793ce26728100ec
Actual:      cd75a560ba59f0b3030c022e8919657e6eedd3f48c95dd0fc2acdfa51c33a326

**Comment by kodybrown** [comment]
Thanks for taking the time to create this issue!
Though, I'm sorry for such an absence!
_(I haven't been getting any notifications from GitHub since last August apparently.)_
I've updated all the apps.
