### ISSUE TITLE
taskschedulerview@1.46: hash check failed

### ISSUE THREAD

**Issue by ramgp** [kodybrown/scoop-nirsoft#16]
App:         nirsoft/taskschedulerview
URL:         https://nirsoft.net/utils/taskschedulerview-x64.zip
First bytes: 50 4B 03 04 14 00 02 00
Expected:    9891f52f84ec5a2c830d7ca6e374f4adc7a341cf52ce3310448b297666cc03bb
Actual:      3099f263e6e715579d1a4b2705508963f061f20097691dc0833fa886d1f057e3

**Comment by kodybrown** [comment]
I updated binary and hash. Thank you for creating an issue!
