### ISSUE TITLE
usbdeview@3.05: hash check failed

### ISSUE THREAD

**Issue by aqshl** [kodybrown/scoop-nirsoft#163]
PS C:\Users\Aqshal> scoop install usbdeview
Updating Scoop...
Updating 'extras' bucket...
 * b8c529beb qownnotes: Update to version 22.9.0                         4 hours ago
 * f25d99ecd openlens: Update to version 6.0.2                           4 hours ago
 * 944075cce listen1desktop: Update to version 2.26.1                    4 hours ago
 * aa913a4e3 konversation: Update to version 22.08.1-1242                4 hours ago
 * d9a885bb1 jackett: Update to version 0.20.1861                        4 hours ago
 * 38df8e1a4 ghostwriter: Update to version 2.1.5                        4 hours ago
 * 202e3172b foobar2000-encoders: Update to version 2022-09-10           4 hours ago
 * 26b79b20a filelight: Update to version 22.08.1-1101                   4 hours ago
 * 7704b60a6 fclones: Update to version 0.27.3                           4 hours ago
 * d74751c77 capframex: Update to version 1.6.9                          4 hours ago
 * b84603586 babelmap: Update to version 15.0.0.1                        4 hours ago
 * c0366927b moar: Add version 1.9.7 (#9190)                             7 hours ago
 * 4088149e7 dngrep: Fix persist                                         7 hours ago
 * 78f963fd9 cudatext: Update to version 1.170.5.0                       8 hours ago
 * 7f1aeeb30 ani-cli: Update depends and suggest (#9212)                 10 hours ago
 * 682b3ed1d openlens: Add version 6.0.1 (#9180)                         11 hours ago
 * f1a52d12e netron: Update to version 6.0.4                             12 hours ago
 * af505b76c autohotkey2: Update to version 2.0-beta.9                   12 hours ago
 * 7989c038e btop4win: Add version 1.0.2 (#9200)                         12 hours ago
 * 0b306d9c5 ani-cli: Update to version 3.4 (#9198)                      12 hours ago
 * 36888ffa5 cider: Add version 1.5.6 (#9154)                            12 hours ago
 * f178841c9 restish: Add version 0.14.0 (#9188)                         12 hours ago
 * e7833f8a8 010editor: Update to version 13.0, Fix autoupdate (#9197)   14 hours ago
 * 71bd55e1a wechat: Update to 3.7.6.44, Fix checkver autoupdate (#9196) 14 hours ago
 * ff5dd1bb3 netron: Update to version 6.0.3                             15 hours ago
 * d6701b4e9 hysteria: Update to version 1.2.1                           15 hours ago
 * 9c51ba6fd elasticsearch: Add missing shims (#9211)                    16 hours ago
 * 6c72096cd xmlnotepad: Update to version 2.8.0.62                      19 hours ago
 * 7ab39de37 x64dbg: Update to version 2022-09-10_01-57                  19 hours ago
 * ac8b3efb7 siyuan-note: Update to version 2.1.14                       19 hours ago
 * 0912b5711 discordchatexporter: Update to version 2.35.2               19 hours ago
 * 1c9a969ad ani-cli: Update to version 3.4                              19 hours ago
 * 579e54624 webex@42.8.0.23281: Fix hash (Closes #9208)                 23 hours ago
 * ecff833c0 x64dbg: Update to version 2022-09-09_17-17                  24 hours ago
Updating 'main' bucket...
 * 7c8e93097 dmd: Update to version 2.100.2                              4 hours ago
 * 874054560 wireproxy: Add version 1.0.5 (#3896)                        7 hours ago
 * e505d8db3 powersession-rs: Update to version 0.1.7                    8 hours ago
 * 704672308 gawk: Update to version 5.2.0                               8 hours ago
 * a236c6c52 marp: Update to version 2.1.4                               12 hours ago
 * d58225e88 rizin: Update to version 0.4.1                              15 hours ago
 * af0a8f992 nixpacks: Update to version 0.4.8                           15 hours ago
 * b7b4750e1 julia: Update to version 1.8.1                              15 hours ago
 * 4671e8295 genact: Update to version 1.0.2                             15 hours ago
 * 60e0894e6 emscripten: Update to version 3.1.21                        20 hours ago
 * 93e38fdea edgedriver: Update to version 107.0.1379.0                  20 hours ago
 * 3d30f2d42 micronaut: Update to version 3.6.3                          24 hours ago
 * 673968fd4 loft: Update to version 2.3.0                               24 hours ago
 * 9f9961ba8 liquibase: Update to version 4.16.0                         24 hours ago
 * 812e31cdc cloud-sql-proxy: Update to version 1.32.0                   24 hours ago
 * fbc0fbc3f aws: Update to version 2.7.31                               24 hours ago
Updating 'nirsoft' bucket...
Scoop was updated successfully!
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
WARN  To disable this warning, run 'scoop config aria2-warning-enabled false'.
Installing 'usbdeview' (3.05) [64bit] from nirsoft bucket
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 7604a2|OK  |   124KiB/s|C:/Users/Aqshal/scoop/cache/usbdeview#3.05#https_www.nirsoft.net_utils_usbdeview-x64.zip
Download: 401eee|OK  |   537KiB/s|C:/Users/Aqshal/scoop/cache/usbdeview#3.05#http_www.linux-usb.org_usb.ids
Download: Status Legend:
Download: (OK):download completed.
Checking hash of usbdeview-x64.zip ... ERROR Hash check failed!
App:         nirsoft/usbdeview
URL:         https://www.nirsoft.net/utils/usbdeview-x64.zip
First bytes: 50 4B 03 04 14 00 02 00
Expected:    0ed3fae58c46d70e5b8c1988c8780e5de4310b80e23404669b8bb993d587be48
Actual:      f48ef907767754be0831fb9e64399f3a9204174189fd5e247d91bfe2855f7e26

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/kodybrown/scoop-nirsoft/issues/new?title=usbdeview%403.05%3a+hash+check+failed

**Comment by themrvideouser** [comment]
New Version 3.06

**Comment by kodybrown** [comment]
Thanks for taking the time to create this issue!
Though, I'm sorry for such an absence!
_(I haven't been getting any notifications from GitHub since last August apparently.)_
I've updated all the apps.
