### ISSUE TITLE
simplewmiview@1.51: hash check failed

### ISSUE THREAD

**Issue by nixeo** [kodybrown/scoop-nirsoft#164]
Checking hash of simplewmiview-x64.zip ... ERROR Hash check failed!
App:         nirsoft/simplewmiview
URL:         https://www.nirsoft.net/utils/simplewmiview-x64.zip
First bytes: 50 4B 03 04 14 00 02 00
Expected:    9f0956ee19cf384d3ba43960ab7375219da63742fad9b124d87554dc87999b95
Actual:      88ea6bb72e6c7518181d140512142233105292a1b5427e7a51df9f29e3a5eb4e

**Comment by kodybrown** [comment]
Thanks for taking the time to create this issue!
Though, I'm sorry for such an absence!
_(I haven't been getting any notifications from GitHub since last August apparently.)_
I've updated all the apps.
