### ISSUE TITLE
alternatestreamview@1.56: hash check failed

### ISSUE THREAD

**Issue by Ack2112** [kodybrown/scoop-nirsoft#174]
App:         nirsoft/alternatestreamview
URL:         https://www.nirsoft.net/utils/alternatestreamview-x64.zip
First bytes: 50 4B 03 04 14 00 02 00
Expected:    9b7d09b3db143585b3ff06fedf954a2ae8d40a704952620927420cddc28759e3
Actual:      c0c5fa2e055e0774e1976d78b9f87c20b657504ef764adc31c03ef4c88513631

**Comment by kodybrown** [comment]
Thanks for taking the time to create this issue!
Though, I'm sorry for such an absence!
_(I haven't been getting any notifications from GitHub since last August apparently.)_
I've updated all the apps.
