### ISSUE TITLE
fulleventlogview@1.71: Hash check failed

### ISSUE THREAD

**Issue by gema-arta** [kodybrown/scoop-nirsoft#175]
Hash check failed!
App:         nirsoft/fulleventlogview
URL:         https://www.nirsoft.net/utils/fulleventlogview-x64.zip
First bytes: 80 75 3 4 20 0 2 0
Expected:    ec128bda81ea193b8dbac9ff120b3c8c7513f244c3a7a560b9033dbb2f60decc
Actual:      86f1f11027f384fd82abe1ff34aec559dddadd16e3535c2f4ddd4235c5abf66f

**Comment by kodybrown** [comment]
Thanks for taking the time to create this issue!
Though, I'm sorry for such an absence!
_(I haven't been getting any notifications from GitHub since last August apparently.)_
I've updated all the apps.
