### ISSUE TITLE
searchmyfiles@3.17: hash check failed

### ISSUE THREAD

**Issue by fabienbernard** [kodybrown/scoop-nirsoft#176]
Hello,

I just tried installing SearchMyFiles using scoop, and got this hash error:

scoop install searchmyfiles
Installing 'searchmyfiles' (3.17) [64bit] from nirsoft bucket
searchmyfiles-x64.zip (148,8 KB) [=======================================================================================================================================================================] 100%
Checking hash of searchmyfiles-x64.zip ... ERROR Hash check failed!
App:         nirsoft/searchmyfiles
URL:         https://www.nirsoft.net/utils/searchmyfiles-x64.zip
First bytes: 50 4B 03 04 14 00 02 00
Expected:    acebecb9079c79517b2c45678e7b14f212c40d37592a58bfd793ce26728100ec
Actual:      c2dfccf2f68ab90d7aef81d8272ab79231abab8300e8f1159d4011f840d76c8e

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/kodybrown/scoop-nirsoft/issues/new?title=searchmyfiles%403.17%3a+hash+check+failed

Tried again, with the same result.

**Comment by kodybrown** [comment]
Thanks for taking the time to create this issue!
Though, I'm sorry for such an absence!
_(I haven't been getting any notifications from GitHub since last August apparently.)_
I've updated all the apps.
