### ISSUE TITLE
Description of application shown in start menu

### ISSUE THREAD

**Issue by he3als** [kodybrown/scoop-nirsoft#178]
Having the description of the application shown in the start menu makes it look too cluttered.

I might make a pull request to fix this in the future.

![image](https://user-images.githubusercontent.com/65787561/200410125-007d0680-9ec7-4ed1-9f02-a9036a0563aa.png)

**Comment by kodybrown** [comment]
Thank you for the suggestion!
I agree that it does make it more cluttered, but I like being able to search for the utilities in the start menu. Because I often can't remember the exact name.
