### ISSUE TITLE
chromecookiesview@1.70: hash check failed

### ISSUE THREAD

**Issue by areen-c** [kodybrown/scoop-nirsoft#179]
Download: (OK):download completed.
Checking hash of chromecookiesview.zip ... ERROR Hash check failed!
App:         nirsoft/chromecookiesview
URL:         https://www.nirsoft.net/utils/chromecookiesview.zip
First bytes: 50 4B 03 04 14 00 02 00
Expected:    b26c49a58d70018a5d3d44c8436a19ed37a8afd85ca41cbca90148e63ba687dc
Actual:      a97389840d8cb3c8ce947c6c2b7c3b808c21af105fa1bf5e4be8fc1b57126efa

**Comment by kodybrown** [comment]
Thanks for taking the time to create this issue!
Though, I'm sorry for such an absence!
_(I haven't been getting any notifications from GitHub since last August apparently.)_
I've updated all the apps.
