### ISSUE TITLE
filetypesman@1.83: hash check failed

### ISSUE THREAD

**Issue by stosc** [kodybrown/scoop-nirsoft#18]
Installing 'filetypesman' (1.83) [64bit]
filetypesman-x64.zip (93.7 KB) [==============================================================================] 100%
Checking hash of filetypesman-x64.zip ... ERROR Hash check failed!
App:         nirsoft/filetypesman
URL:         https://www.nirsoft.net/utils/filetypesman-x64.zip
First bytes: 50 4B 03 04 14 00 02 00
Expected:    a92b316f3b14ace527df18fd39f9dee3af6153a758d4301df54718a9eb07a605
Actual:      3b3930ec9dff2eb32c264e175ceb984bc71a7982e7f8425b7dae5376ad410f8d

**Comment by kodybrown** [comment]
I updated binary and hash. Thank you for creating an issue!
