### ISSUE TITLE
wifidiagnosticsview@1.01: hash check failed

### ISSUE THREAD

**Issue by igitur** [kodybrown/scoop-nirsoft#180]
C:\〉scoop install wifidiagnosticsview 
WARN  Purging previous failed installation of wifidiagnosticsview.
ERROR 'wifidiagnosticsview' isn't installed correctly.
Removing older version (1.01).
'wifidiagnosticsview' was uninstalled.
Installing 'wifidiagnosticsview' (1.01) [64bit] from nirsoft bucket
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: f73d43|OK  |   140KiB/s|C:/scoop/cache/wifidiagnosticsview#1.01#https_www.nirsoft.net_utils_wifidiagnosticsview.zip
Download: Status Legend:
Download: (OK):download completed.
Checking hash of wifidiagnosticsview.zip ... ERROR Hash check failed!
App:         nirsoft/wifidiagnosticsview
URL:         https://www.nirsoft.net/utils/wifidiagnosticsview.zip
First bytes: 50 4B 03 04 14 00 02 00
Expected:    5ea1d65f947cc3724c5ee7528e9b07cc3438cbeff267f2d88cd6e02ad82b94f2
Actual:      154a7333a4a435857f664df5810cd0c5353e5566a3ff34f24a2718d2f3b02899

**Comment by kodybrown** [comment]
Thanks for taking the time to create this issue!
Though, I'm sorry for such an absence!
_(I haven't been getting any notifications from GitHub since last August apparently.)_
I've updated all the apps.

**Comment by igitur** [comment]
Thanks for the updates! I love having access to the nirsoft toolset via scoop. So convenient.
