### ISSUE TITLE
devmanview@1.76: hash check failed

### ISSUE THREAD

**Issue by Not-a-Tyler** [kodybrown/scoop-nirsoft#182]
scoop install devmanview
WARN  Purging previous failed installation of devmanview.
ERROR 'devmanview' isn't installed correctly.
Removing older version (1.76).
'devmanview' was uninstalled.
Installing 'devmanview' (1.76) [64bit] from nirsoft bucket
devmanview-x64.zip (98.8 KB) [================================================================================] 100%
Checking hash of devmanview-x64.zip ... ERROR Hash check failed!
App:         nirsoft/devmanview
URL:         https://www.nirsoft.net/utils/devmanview-x64.zip
First bytes: 50 4B 03 04 14 00 02 00
Expected:    a7dd51ea5ab57fe2f686fbb8dc0d5e96207d77d317da9e83c636f98bda4c5a4c
Actual:      e230bcdf0d9a5b5ee8d4f13220667843418f2dd3c9a6f24808574e312d298343

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/kodybrown/scoop-nirsoft/issues/new?title=devmanview%401.76%3a+hash+check+failed

**Comment by kodybrown** [comment]
Thanks for taking the time to create this issue!
Though, I'm sorry for such an absence!
_(I haven't been getting any notifications from GitHub since last August apparently.)_
I've updated all the apps.
