### ISSUE TITLE
Should scoop switch its nirsoft bucket?

### ISSUE THREAD

**Issue by rasa** [kodybrown/scoop-nirsoft#184]
Hey Kody,

I hope all is well. Hey, I posted this question to 
https://github.com/ScoopInstaller/Scoop/discussions/5293
Please let us know your thoughts. 

Best wishes,
Ross

**Comment by kodybrown** [comment]
Thanks for taking the time to create this issue!
Though, I'm sorry for such an absence!
_(I haven't been getting any notifications from GitHub since last August apparently.)_
I've updated all the apps.

**Comment by kodybrown** [comment]
Thank you for that! I replied there.
