### ISSUE TITLE
networktrafficview@2.41: hash check failed

### ISSUE THREAD

**Issue by kazum1kun** [kodybrown/scoop-nirsoft#185]
Another hash check failed, please fix it. Thanks

App:         nirsoft/networktrafficview
URL:         https://www.nirsoft.net/utils/networktrafficview-x64.zip
First bytes: 50 4B 03 04 14 00 02 00
Expected:    1ec419404d0545ecce98d1c37a3210b8163c7be038ebfdfdf20531972f333ef1
Actual:      596665c3f7af49a3daa0eeb146c6ade266a9dd59d59a17ab4ff1e09ee17a4716

**Comment by kodybrown** [comment]
Thank you both for taking the time to create this issue and a PR!
Though, I'm sorry for such an absence!
_(I haven't been getting any notifications from GitHub since last August apparently.)_
I've updated all the apps.
