### ISSUE TITLE
openedfilesview@1.86: hash check failed

### ISSUE THREAD

**Issue by info-kubu-at** [kodybrown/scoop-nirsoft#186]
PS C:\Users\user> scoop install openedfilesview
WARN  Purging previous failed installation of openedfilesview.
ERROR 'openedfilesview' isn't installed correctly.
Removing older version (1.86).
'openedfilesview' was uninstalled.
Installing 'openedfilesview' (1.86) [64bit] from nirsoft bucket
ofview-x64.zip (96,6 KB) [====================================================================================================================================================================================================================================================] 100%
Checking hash of ofview-x64.zip ... ERROR Hash check failed!
App:         nirsoft/openedfilesview
URL:         https://www.nirsoft.net/utils/ofview-x64.zip
First bytes: 50 4B 03 04 14 00 02 00
Expected:    a250cfe10a4cf8fe3044508c1d07bddce45809467d867977bed1fa9f5f6d2c9c
Actual:      1cd0a58bfeecb1cbcf5d0311cd3bb830619d443a48cab77801544a5f67af890c

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/kodybrown/scoop-nirsoft/issues/new?title=openedfilesview%401.86%3a+hash+check+failed

**Comment by he3als** [comment]
Same here:
```
ERROR Hash check failed!
App:         nirsoft/openedfilesview
URL:         https://www.nirsoft.net/utils/ofview-x64.zip
First bytes: 50 4B 03 04 14 00 02 00
Expected:    a250cfe10a4cf8fe3044508c1d07bddce45809467d867977bed1fa9f5f6d2c9c
Actual:      1cd0a58bfeecb1cbcf5d0311cd3bb830619d443a48cab77801544a5f67af890c

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/kodybrown/scoop-nirsoft/issues/new?title=openedfilesview%401.86%3a+hash+check+failed
```

**Comment by kodybrown** [comment]
Thank you both for taking the time to create this issue and a PR!
Though, I'm sorry for such an absence!
_(I haven't been getting any notifications from GitHub since last August apparently.)_
I've updated all the apps.
