### ISSUE TITLE
exifdataview@1.11: hash check failed

### ISSUE THREAD

**Issue by rjperrella** [kodybrown/scoop-nirsoft#187]
Checking hash of exifdataview.zip ... ERROR Hash check failed!
App:         nirsoft/exifdataview
URL:         https://www.nirsoft.net/utils/exifdataview.zip
First bytes: 50 4B 03 04 14 00 02 00
Expected:    f244a806e8ef8e1a85df67dfa96e40bbf4cf9196905ebcf18d4a81c91aa69261
Actual:      0f45ca559056837401f3934a39db0b74ba24ecfde97dc6bc2e7211f2ae9e7e47

**Comment by kodybrown** [comment]
Thank you both for taking the time to create this issue and a PR!
Though, I'm sorry for such an absence!
_(I haven't been getting any notifications from GitHub since last August apparently.)_
I've updated all the apps.
