### ISSUE TITLE
filetypesman@1.96: hash check failed

### ISSUE THREAD

**Issue by surayut99** [kodybrown/scoop-nirsoft#188]
I got this error message when I was trying to install `filetypesman` using `scoop`

```
App:         nirsoft/filetypesman
URL:         https://www.nirsoft.net/utils/filetypesman-x64.zip
First bytes: 50 4B 03 04 14 00 02 00
Expected:    5feec2a7c0ca1d46ff8bd27a0eadd068f3d8c6dc3fee6f7354973319aeecefb3
Actual:      4ecf354e78796ad36c96a02b9b3ab4df0e71872a99cf5b7428de6ac2ae29a31d
```

**Comment by kodybrown** [comment]
Thank you both for taking the time to create this issue and a PR!
Though, I'm sorry for such an absence!
_(I haven't been getting any notifications from GitHub since last August apparently.)_
I've updated all the apps.
