### ISSUE TITLE
netrouteview@1.35: hash check failedPS

### ISSUE THREAD

**Issue by mnishig** [kodybrown/scoop-nirsoft#193]
I met these error while it install NetRouteView with scoop.
Following logs I got.
---------
> scoop bucket add nirsoft
The nirsoft bucket was added successfully.
> scoop install netrouteview
WARN  Purging previous failed installation of netrouteview.
ERROR 'netrouteview' isn't installed correctly.
Removing older version (1.35).
'netrouteview' was uninstalled.
Installing 'netrouteview' (1.35) [64bit] from nirsoft bucket
netrouteview.zip (51.5 KB) [==============================================================] 100%
Checking hash of netrouteview.zip ... ERROR Hash check failed!
App:         nirsoft/netrouteview
URL:         https://www.nirsoft.net/utils/netrouteview.zip
First bytes: 50 4B 03 04 14 00 02 00
Expected:    c1a4a90097d1e589d4e4cc90a91256018232462fbc86e5849ac41bac8b88751e
Actual:      266d4972ef251f950d63f3c5491da99dffceb3c505f7d8118fc9eccdb476101a

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/kodybrown/scoop-nirsoft/issues/new?title=netrouteview%401.35%3a+hash+check+failed

**Comment by kodybrown** [comment]
Thank you both for taking the time to create this issue and a PR!
Though, I'm sorry for such an absence!
_(I haven't been getting any notifications from GitHub since last August apparently.)_
I've updated all the apps.
