### ISSUE TITLE
outlookattachview@3.44: hash check failed

### ISSUE THREAD

**Issue by ffalcon31415** [kodybrown/scoop-nirsoft#202]
>scoop install outlookattachview
WARN  Purging previous failed installation of outlookattachview.
ERROR 'outlookattachview' isn't installed correctly.
Removing older version (3.44).
'outlookattachview' was uninstalled.
Installing 'outlookattachview' (3.44) [64bit] from nirsoft bucket
outlookattachview-x64.zip (171.9 KB) [========================================================================] 100%
Checking hash of outlookattachview-x64.zip ... ERROR Hash check failed!
App:         nirsoft/outlookattachview
URL:         https://www.nirsoft.net/utils/outlookattachview-x64.zip
First bytes: 50 4B 03 04 14 00 02 00
Expected:    f927ec669d560be9d51fce16b33ebf7dbf6d197ca361b55c10ffd33ffcc783a8
Actual:      d1a71689d1b89707d123e087270edc5808d0a0c25a6265ee26264d3aee4cafd2

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/kodybrown/scoop-nirsoft/issues/new?title=outlookattachview%403.44%3a+hash+check+failed

**Comment by kodybrown** [comment]
Thank you both for taking the time to create this issue and a PR!
Though, I'm sorry for such an absence!
_(I haven't been getting any notifications from GitHub since last August apparently.)_
I've updated all the apps.
