### ISSUE TITLE
dnsdataview@1.65: hash check failed

### ISSUE THREAD

**Issue by marslvl2** [kodybrown/scoop-nirsoft#206]
PS C:\Users\(redacted)> scoop uninstall dnsdataview
ERROR 'dnsdataview' isn't installed.
PS C:\Users\mars> scoop install dnsdataview
Installing 'dnsdataview' (1.65) [64bit] from nirsoft bucket
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 86b6bb|OK  |   600KiB/s|C:/Users/(redacted)/scoop/cache/dnsdataview#1.65#https_www.nirsoft.net_utils_dnsdataview.zip
Download: Status Legend:
Download: (OK):download completed.
Checking hash of dnsdataview.zip ... ERROR Hash check failed!
App:         nirsoft/dnsdataview
URL:         https://www.nirsoft.net/utils/dnsdataview.zip
First bytes: 50 4B 03 04 14 00 02 00
Expected:    4b6076a878fb064e63089ef1cdc25792d0bdb7d54d771441e7e0d2232c7a470e
Actual:      16211c5247abcd909cdd5ea2ab02bf89e0f0156eedd0891a4c32bb3a23761b7d

**Comment by kodybrown** [comment]
Thank you both for taking the time to create this issue and a PR!
Though, I'm sorry for such an absence!
_(I haven't been getting any notifications from GitHub since last August apparently.)_
I've updated all the apps.
