### ISSUE TITLE
ControlMyMonitor@1.35: hash check failed

### ISSUE THREAD

**Issue by cvladan** [kodybrown/scoop-nirsoft#215]
Installing 'ControlMyMonitor' (1.35) [64bit] from nirsoft bucket
controlmymonitor.zip (76.9 KB) [==========================================================================================================================================================================================================================================================] 100%
Checking hash of controlmymonitor.zip ... ERROR Hash check failed!
App:         nirsoft/ControlMyMonitor
URL:         https://www.nirsoft.net/utils/controlmymonitor.zip
First bytes: 50 4B 03 04 14 00 02 00
Expected:    b81509b058acbe221e0e189565d050354f7a82a4f719872496fd7adf575675dd
Actual:      f740f305e278668e8580ccfc3c458bbb1106cabd223fab31f8680c58cb9bc79c

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/kodybrown/scoop-nirsoft/issues/new?title=ControlMyMonitor%401.35%3a+hash+check+failed
PS C:\Storage\Temporary>

**Comment by pedoc** [comment]
scoop install xxx -s //-s option skip hash verify

**Comment by cvladan** [comment]
Yes, I know. Thanks.
I just wanted to contribute by informing about it.

**Comment by pedoc** [comment]
It looks like the author of the current repo is so busy that he doesn't have time to maintain this repo.

alternatives:
https://github.com/ScoopInstaller/Nirsoft/

**Comment by cvladan** [comment]
I don't understand? This one is not official?
Why then is this one installed by default?

![image](https://user-images.githubusercontent.com/1913156/221506284-38fedf5a-3c62-4231-8471-7329b35400b3.png)

**Comment by kodybrown** [comment]
Sorry about this everyone...

Thank you both for taking the time to create this issue and a PR!
Though, I'm sorry for such an absence!
_(I haven't been getting any notifications from GitHub since last August apparently.)_

I've updated all the apps.
