### ISSUE TITLE
wifiinfoview@2.76: hash check failed

### ISSUE THREAD

**Issue by matdave** [kodybrown/scoop-nirsoft#217]
Installing 'wifiinfoview' (2.76) [64bit] from nirsoft bucket
wifiinfoview-x64.zip (483.5 KB) [=============================================================================] 100%
Checking hash of wifiinfoview-x64.zip ... ERROR Hash check failed!
App:         nirsoft/wifiinfoview
URL:         https://www.nirsoft.net/utils/wifiinfoview-x64.zip
First bytes: 50 4B 03 04 14 00 02 00
Expected:    3febc8004e3f98fdbe10509472e25bb5396bbd53b3cb64bc607db90cb5da1fe7
Actual:      2c1ad4bba2af198127affe8619b3863c415d73192e8d74c5025c7a4f93ef31a9

**Comment by kodybrown** [comment]
Thanks for taking the time to create this issue!
Though, I'm sorry for such an absence!
_(I haven't been getting any notifications from GitHub since last August apparently.)_
I've updated all the apps.
