### ISSUE TITLE
taskschedulerview@1.71: hash check failed

### ISSUE THREAD

**Issue by pstaszko** [kodybrown/scoop-nirsoft#218]
I"m seeing the actual has is now this:
02775eef03c483914a40151f6b54465fffcd85e8429c05e6a868dc32416a1031
The version is 1.72

**Comment by kodybrown** [comment]
Thank you both for taking the time to create this issue and a PR!
Though, I'm sorry for such an absence!
_(I haven't been getting any notifications from GitHub since last August apparently.)_
I've updated all the apps.
