### ISSUE TITLE
UninstallView@1.24: hash check failed

### ISSUE THREAD

**Issue by fourtf** [kodybrown/scoop-nirsoft#22]
Checking hash of uninstallview-x64.zip ... ERROR Hash check failed!                                                     App: nirsoft/UninstallView
URL: https://nirsoft.net/utils/uninstallview-x64.zip                                                            First bytes: 50 4B 03 04 14 00 02 00                                                                                    Expected: 3981ca9af254826b0728aceb6efebbfb48a57669a97fc6357a7cb248d4fa0360                                           Actual: e4ecd9b59c55bee08f7ad4317926cbe5d5eeb363fdb3450a587f49e68d3aa1c6

**Comment by dannykorpan** [comment]
Has current version 1.35
d9683cba1f6bcf893fed0bec15cab1ecc8cd5b311d87f4bde8f55eef8217fbe2

**Comment by kodybrown** [comment]
I updated binary and hash. Thank you for creating an issue!
