### ISSUE TITLE
searchmyfiles@3.17: hash check failed

### ISSUE THREAD

**Issue by heinzhi** [kodybrown/scoop-nirsoft#224]
Removing older version (3.17).
'searchmyfiles' was uninstalled.
Installing 'searchmyfiles' (3.17) [64bit] from nirsoft bucket
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 41f7dd|OK  |   386KiB/s|C:/Users/[XXX]/scoop/cache/searchmyfiles#3.17#https_www.nirsoft.net_utils_searchmyfiles-x64.zip
Download: Status Legend:
Download: (OK):download completed.
Checking hash of searchmyfiles-x64.zip ... ERROR Hash check failed!
App:         nirsoft/searchmyfiles
URL:         https://www.nirsoft.net/utils/searchmyfiles-x64.zip
First bytes: 50 4B 03 04 14 00 02 00
Expected:    acebecb9079c79517b2c45678e7b14f212c40d37592a58bfd793ce26728100ec
Actual:      ebe9220d7fe319d61552ab30eae9dee0d18e264b4a5ae172884c34a66c69ad57

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/kodybrown/scoop-nirsoft/issues/new?title=searchmyfiles%403.17%3a+hash+check+failed

**Comment by kodybrown** [comment]
Thank you both for taking the time to create this issue and a PR!
Though, I'm sorry for such an absence!
_(I haven't been getting any notifications from GitHub since last August apparently.)_
I've updated all the apps.
