### ISSUE TITLE
webbrowserpassview@2.11: hash check failed

### ISSUE THREAD

**Issue by kjadfksjd** [kodybrown/scoop-nirsoft#225]
`scoop install webbrowserpassview
Installing 'webbrowserpassview' (2.11) [64bit] from nirsoft bucket
webbrowserpassview.zip (273,4 KB) [===========================================================================] 100%
Checking hash of webbrowserpassview.zip ... ERROR Hash check failed!
App:         nirsoft/webbrowserpassview
URL:         https://www.nirsoft.net/toolsdownload/webbrowserpassview.zip
First bytes: 50 4B 03 04 14 00 01 00
Expected:    3b7c7ff46716908d825e7303dd920a75b30af8f1d106a154c714473563191c0b
Actual:      ae05a1f901bdcd1b40c598b6563c08fbaac998e3e4c7fda36ab967f8f174940f

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/kodybrown/scoop-nirsoft/issues/new?title=webbrowserpassview%402.11%3a+hash+check+failed`

**Comment by kjadfksjd** [comment]
Okay there's is password:
Zip File Password: `wbpv28821@`

**Comment by kodybrown** [comment]
Thank you both for taking the time to create this issue and a PR!
Though, I'm sorry for such an absence!
_(I haven't been getting any notifications from GitHub since last August apparently.)_
I've updated all the apps.
