### ISSUE TITLE
USBDeview@3.05: hash check failed

### ISSUE THREAD

**Issue by Lan-Hekary** [kodybrown/scoop-nirsoft#226]
App:         nirsoft/USBDeview
URL:         https://www.nirsoft.net/utils/usbdeview-x64.zip
First bytes: 50 4B 03 04 14 00 02 00
Expected:    0ed3fae58c46d70e5b8c1988c8780e5de4310b80e23404669b8bb993d587be48
Actual:      f48ef907767754be0831fb9e64399f3a9204174189fd5e247d91bfe2855f7e26

**Comment by kodybrown** [comment]
Thank you both for taking the time to create this issue and a PR!
Though, I'm sorry for such an absence!
_(I haven't been getting any notifications from GitHub since last August apparently.)_
I've updated all the apps.
