### ISSUE TITLE
currports@2.65: hash check failed

### ISSUE THREAD

**Issue by unrealchenyu** [kodybrown/scoop-nirsoft#227]
App:         nirsoft/currports
URL:         https://www.nirsoft.net/utils/cports-x64.zip
First bytes: 50 4B 03 04 14 00 02 00
Expected:    6288c8beaf775443201791d282b3c48508de37636376577c4319b19c525548db
Actual:      c2dc79b418a45b2b344e8301619447978c1a7f6526d1e1a35671344c4c5a906d

**Comment by kodybrown** [comment]
Thank you both for taking the time to create this issue and a PR!
Though, I'm sorry for such an absence!
_(I haven't been getting any notifications from GitHub since last August apparently.)_
I've updated all the apps.
