### ISSUE TITLE
volumouse@2.03: hash check failed

### ISSUE THREAD

**Issue by APP32Piotr** [kodybrown/scoop-nirsoft#242]
Installing 'volumouse' (2.03) [64bit] from nirsoft bucket
volumouse-x64.zip (68,6 KB) [=================================================] 100%
Checking hash of volumouse-x64.zip ... ERROR Hash check failed!
App:         nirsoft/volumouse
URL:         https://www.nirsoft.net/utils/volumouse-x64.zip
First bytes: 50 4B 03 04 14 00 02 00
Expected:    1e2ffa45d062316a95b23d5219f6dc962eb22206169a95fb102d515cd3d542a2
Actual:      e9dce5eff147c14de2b27018500ae5a34852d34d102e6fa65d2fdb7e61c554f3

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/kodybrown/scoop-nirsoft/issues/new?title=volumouse%402.03%3a+hash+check+failed

**Comment by kodybrown** [comment]
Thank you both for taking the time to create this issue and a PR!
Though, I'm sorry for such an absence!
_(I haven't been getting any notifications from GitHub since last August apparently.)_
I've updated all the apps.
