### ISSUE TITLE
countrytraceroute@1.32: hash check failed

### ISSUE THREAD

**Issue by BurningProcessor** [kodybrown/scoop-nirsoft#245]
24.05.2023

PS > scoop install countrytraceroute
WARN  Purging previous failed installation of countrytraceroute.
ERROR You need admin rights to uninstall global apps.
WARN  Purging previous failed installation of countrytraceroute.
ERROR You need admin rights to uninstall global apps.
Installing 'countrytraceroute' (1.32) [64bit] from nirsoft bucket
countrytraceroute.zip (466,5 KB) [=================================================================================================] 100%
Checking hash of countrytraceroute.zip ... ERROR Hash check failed!
App:         nirsoft/countrytraceroute
URL:         https://www.nirsoft.net/utils/countrytraceroute.zip
First bytes: 50 4B 03 04 14 00 02 00
Expected:    df02f698aec6c332af9ee9b4b770ed6205853390588951a237af36218a2cd98c
Actual:      754572dc0385b0653ceb1d4f0f72272f46fda9b7ea1c55c922d8adfc8a1a1c99

**Comment by kodybrown** [comment]
Thank you both for taking the time to create this issue and a PR!
Though, I'm sorry for such an absence!
_(I haven't been getting any notifications from GitHub since last August apparently.)_
I've updated all the apps.
