### ISSUE TITLE
pinginfoview@2.00: hash check failed

### ISSUE THREAD

**Issue by WisdomKwan** [kodybrown/scoop-nirsoft#25]
λ scoop install pinginfoview
Installing 'pinginfoview' (2.00) [64bit]
pinginfoview.zip (61.7 KB) [===================================================================================================================] 100%
Checking hash of pinginfoview.zip ... ERROR Hash check failed!
App:         nirsoft/pinginfoview
URL:         https://www.nirsoft.net/utils/pinginfoview.zip
First bytes: 50 4B 03 04 14 00 02 00
Expected:    368ead65fd2295c4270183dc7e461b4b82680c8f531b463605237ee4c401d04c
Actual:      9c074b15ff6d0bbf74f668a51907581f85eabec7cbaec42e4a03454719a95f45

**Comment by kodybrown** [comment]
I updated binary and hash. Thank you for creating an issue!
