### ISSUE TITLE
usbdeview@3.07: hash check failed

### ISSUE THREAD

**Issue by ihndry** [kodybrown/scoop-nirsoft#256]
Starting package install operation for package id=usbdeview with Manager name=Scoop
Given installation options are <InstallationOptions: SkipHashCheck=False;InteractiveInstallation=False;RunAsAdministrator=False;Version=;Architecture=;InstallationScope=;InstallationScope=;CustomParameters=;RemoveDataOnUninstall=False>
Process Executable     : C:\Windows\system32\windowspowershell\v1.0\powershell.exe
Process Call Arguments :  -NoProfile -ExecutionPolicy Bypass -Command scoop install nirsoft/usbdeview
Working Directory      : C:\Users\neo
Process Start Time     : 13.07.2024 01:26:14
    | WARN  Purging previous failed installation of usbdeview.
    | ERROR 'usbdeview' isn't installed correctly.
    | Removing older version (3.07).
    | 'usbdeview' was uninstalled.
    | Installing 'usbdeview' (3.07) [64bit] from 'nirsoft' bucket
    | Loading usbdeview-x64.zip from cache
    | Checking hash of usbdeview-x64.zip ... ok.
    | Downloading http://www.linux-usb.org/usb.ids (711,6 KB)...
    | Checking hash of usb.ids ... ERROR Hash check failed!
    | App:         nirsoft/usbdeview
    | URL:         http://www.linux-usb.org/usb.ids
    | First bytes: 23 0A 23 09 4C 69 73 74
    | Expected:    e6e87ecea1476bc317d6dd22652726060d4b4ffad0566dd6e7d7b1afee1ec8c1
    | Actual:      a761bd7660839cd4d6185a89c92d466cbb349e45c2639e4ed85c63c10b6fac0c
    | Please try again or create a new issue by using the following link and paste your console output:
    | https://github.com/kodybrown/scoop-nirsoft/issues/new?title=usbdeview%403.07%3a+hash+check+failed
Process Exit Code      : 1
Process End Time       : 13.07.2024 01:26:16

**Comment by kodybrown** [comment]
Thanks for taking the time to post this. I'll get it updated. However, you should update your local bucket to point to the new official nirsoft bucket. See the top of the readme [here](https://github.com/kodybrown/scoop-nirsoft) to update you local system.
