### ISSUE TITLE
FileTypesMan@1.86: hash check failed

### ISSUE THREAD

**Issue by RandKn** [kodybrown/scoop-nirsoft#27]
scoop install FileTypesMan
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Installing 'FileTypesMan' (1.86) [64bit]
Starting download with aria2 ...
Download: [#00cb66 0B/0B CN:1 DL:0B]
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 00cb66|OK  |   170KiB/s|C:/Users/super/scoop/cache/FileTypesMan#1.86#https_www.nirsoft.net_utils_filetypesman-x64.zip
Download: Status Legend:
Download: (OK):download completed.
Checking hash of filetypesman-x64.zip ... ERROR Hash check failed!
App:         nirsoft/FileTypesMan
URL:         https://www.nirsoft.net/utils/filetypesman-x64.zip
First bytes: 50 4B 03 04 14 00 02 00
Expected:    3b3930ec9dff2eb32c264e175ceb984bc71a7982e7f8425b7dae5376ad410f8d
Actual:      7d7a7108bea3269289fefe0ee9682bfed156b9a856e0492e8d0974712ba103c5

**Comment by kodybrown** [comment]
I updated binary and hash. Thank you for creating an issue!
