### ISSUE TITLE
Filetypesman@1.80: hash check failed

### ISSUE THREAD

**Issue by akhan3** [kodybrown/scoop-nirsoft#3]
```
λ  ShellExView RegDllView  ShellMenuView  OpenedFilesView
Installing 'Filetypesman' (1.80) [64bit]
filetypesman-x64.zip (94.2 KB) [===================================================================================================================] 100%
Checking hash of filetypesman-x64.zip ... ERROR Hash check failed!
App:         Nirsoft/Filetypesman
URL:         http://www.nirsoft.net/utils/filetypesman-x64.zip
First bytes: 50 4B 03 04 14 00 02 00
Expected:    cc779868a59ef4b2d213ba3d6be3666285c7d0f0491e8d378e2247406eed4c9c
Actual:      a92b316f3b14ace527df18fd39f9dee3af6153a758d4301df54718a9eb07a605

Please create a new issue by using the following link and paste your console output:
https://github.com/kodybrown/scoop-nirsoft/issues/new?title=Filetypesman%401.80%3a+hash+check+failed
```

**Comment by kodybrown** [comment]
Thank you.
Done.

Kody Brown | kodybrown@gmail.com
Sent from Mail for Windows 10

From: Aamir Khan
Sent: Thursday, September 6, 2018 11:58 AM
To: kodybrown/scoop-nirsoft
Cc: Subscribed
Subject: [kodybrown/scoop-nirsoft] Filetypesman@1.80: hash check failed (#3)

λ  ShellExView RegDllView  ShellMenuView  OpenedFilesView
Installing 'Filetypesman' (1.80) [64bit]
filetypesman-x64.zip (94.2 KB) [===================================================================================================================] 100%
Checking hash of filetypesman-x64.zip ... ERROR Hash check failed!
App:         Nirsoft/Filetypesman
URL:         http://www.nirsoft.net/utils/filetypesman-x64.zip
First bytes: 50 4B 03 04 14 00 02 00
Expected:    cc779868a59ef4b2d213ba3d6be3666285c7d0f0491e8d378e2247406eed4c9c
Actual:      a92b316f3b14ace527df18fd39f9dee3af6153a758d4301df54718a9eb07a605

Please create a new issue by using the following link and paste your console output:
https://github.com/kodybrown/scoop-nirsoft/issues/new?title=Filetypesman%401.80%3a+hash+check+failed
