### ISSUE TITLE
dllexportviewer@1.63: hash check failed

### ISSUE THREAD

**Issue by pakdev** [kodybrown/scoop-nirsoft#4]
Checking hash of dllexp-x64.zip ... ERROR Hash check failed!
App:         nirsoft/dllexportviewer
URL:         http://www.nirsoft.net/utils/dllexp-x64.zip
First bytes: 50 4B 03 04 14 00 02 00
Expected:    630e8d48a418adb05fc254f29c0d879ede87848a9ed8a812059b3c56014da816
Actual:      07d4ddd976679891eee2a252de585e1c101089bb4220a4cf3b221473db2bb3fd

**Comment by kodybrown** [comment]
Thank you.
Done.

Kody Brown | kodybrown@gmail.com
Sent from Mail for Windows 10

From: Peter
Sent: Tuesday, October 16, 2018 4:38 PM
To: kodybrown/scoop-nirsoft
Cc: Subscribed
Subject: [kodybrown/scoop-nirsoft] dllexportviewer@1.63: hash check failed(#4)

Checking hash of dllexp-x64.zip ... ERROR Hash check failed!
App: nirsoft/dllexportviewer
URL: http://www.nirsoft.net/utils/dllexp-x64.zip
First bytes: 50 4B 03 04 14 00 02 00
Expected: 630e8d48a418adb05fc254f29c0d879ede87848a9ed8a812059b3c56014da816
Actual: 07d4ddd976679891eee2a252de585e1c101089bb4220a4cf3b221473db2bb3fd
