### ISSUE TITLE
uninstallview@1.36: hash check failed

### ISSUE THREAD

**Issue by benok** [kodybrown/scoop-nirsoft#49]
Installing 'uninstallview' (1.36) [64bit]
uninstallview-x64.zip (110.0 KB) [============================================================================] 100%
Checking hash of uninstallview-x64.zip ... ERROR Hash check failed!
App:         nirsoft/uninstallview
URL:         https://nirsoft.net/utils/uninstallview-x64.zip
First bytes: 50 4B 03 04 14 00 02 00
Expected:    54c23627453c7aa426e5b29a3ad1a7dccf184bea83614ab9f72ebc997b6aecda
Actual:      cbafb75d2242dc778f178aba1a76c0722cb0c6734728030cbd491a43956f3537

**Comment by kodybrown** [comment]
I updated binary and hash. Thank you for creating an issue!
