### ISSUE TITLE
devmanview@1.66: hash check failed

### ISSUE THREAD

**Issue by diVineProportion** [kodybrown/scoop-nirsoft#51]
Installing 'devmanview' (1.66) [64bit]
devmanview-x64.zip (97.3 KB) [================================================================================] 100%
Checking hash of devmanview-x64.zip ... ERROR Hash check failed!
App:         nirsoft/devmanview
URL:         https://www.nirsoft.net/utils/devmanview-x64.zip
First bytes: 50 4B 03 04 14 00 02 00
Expected:    a6e6b5ed9459302c63778012676cb8a183a1adfb0252f6f3a441f5aa5385e757
Actual:      1ed4bac982c428424a93cf9654ef0027a1e0d8447aa0436fa31539c9c4bdaee0

**Comment by kodybrown** [comment]
I updated binary and hash. Thank you for creating an issue!
