### ISSUE TITLE
taskschedulerview@1.54: hash check failed

### ISSUE THREAD

**Issue by PaulWCRI** [kodybrown/scoop-nirsoft#62]
App:         nirsoft/taskschedulerview
URL:         https://nirsoft.net/utils/taskschedulerview-x64.zip
First bytes: 50 4B 03 04 14 00 02 00
Expected:    3726983a9365901c6be2f76565751f1f9a3c82d081e56b46168a31b882c2810a
Actual:      99875249670efd43065bade0dbc54889220e8cadfa5a39c98fe3fed5054456dd

**Comment by kodybrown** [comment]
I updated binary and hash. Thank you for creating an issue!
