### ISSUE TITLE
shellexview@1.97: hash check failed

### ISSUE THREAD

**Issue by fungtion** [kodybrown/scoop-nirsoft#7]
App:         nirsoft/shellexview
URL:         http://www.nirsoft.net/utils/shexview-x64.zip
First bytes: 50 4B 03 04 14 00 02 00
Expected:    a7116d5b8e66fe00fc076ec972832e643f8ba72457d54bb79cba07f9b9745c86
Actual:      75a95c770d062c3f56325b9c1646b606d77f9d918247609676758cdfe44c790e

**Comment by kodybrown** [comment]
I updated binary and hash. Thank you for creating an issue!
