### ISSUE TITLE
produkey@1.95: hash check failed

### ISSUE THREAD

**Issue by ghotz** [kodybrown/scoop-nirsoft#76]
URL:         https://www.nirsoft.net/utils/produkey-x64.zip
First bytes: 50 4B 03 04 14 00 02 00
Expected:    1329ff031c1f1ee14d20e7dc1d5f355836b890ced91b24e460da8df629075b39
Actual:      0cc1d2ccc8a8a8dd8b7e2faec5f478dea3cb246f1bda98009e4787d1270c5a37

**Comment by kodybrown** [comment]
thanks
