### ISSUE TITLE
wirelesskeyview@2.22: password-protected archive & Windows 10 PUP detection

### ISSUE THREAD

**Issue by mjdl** [kodybrown/scoop-nirsoft#81]
https://www.nirsoft.net/utils/wireless_key.html

This program is available in a password (given on that page) protected archive, thus the installation has to somehow stuff in the password during the installation (not sure how that is done in scoop). This is not done, so the installation process stops and has to be terminated via ^C:

C:\Users\mjdl>scoop install wirelesskeyview
Installing 'wirelesskeyview' (2.22) [64bit]
wirelesskeyview-x64.zip (140.1 KB) [==========================================================================] 100%
Checking hash of wirelesskeyview-x64.zip ... ok.
Extracting wirelesskeyview-x64.zip ... Terminate batch job (Y/N)?
^C

But if the archive is extracted, Windows Defender classifies it as a potentially unwanted program, see attached screenshot. An exclusion can be added easily, and the program reinstalled, but the installation still stops at the missing zip archive password
![WindowsDefender-wirelesskeyview-detection](https://user-images.githubusercontent.com/2262328/121822703-82ed7100-cc6e-11eb-9bc4-c4dbccf83724.jpg)

Microsoft probably has some kind of arcane process for automating the Windows Defender  exclusion, but doing it manually works.

There are probably other Nirsoft programs with password protected zip files,  so the problem is general.

**Comment by kodybrown** [comment]
Hmm.. I am not sure what to do about the password requirement...

**Comment by mjdl** [comment]
Me neither, and I don't have the programming chops to find out how. Do Scoop installers  have some kind of interactive command-line features? Or a way of stuffing the zip archive password into the unzipping step?

And then there's the virus detection issue...

Perhaps the best thing is to just close this issue, since resolving it probably involves some kind of enhanced Scoop feature(s).

**Comment by mjdl** [comment]
I'm closing this issue to tidy up your list.
