### ISSUE TITLE
usbdeview@3.01: hash check failed

### ISSUE THREAD

**Issue by jmg99** [kodybrown/scoop-nirsoft#85]
Installing 'usbdeview' (3.01) [64bit]
usbdeview-x64.zip (121,8 KB) [========================================] 100%
Checking hash of usbdeview-x64.zip ... ERROR Hash check failed!
App:         nirsoft/usbdeview
URL:         https://www.nirsoft.net/utils/usbdeview-x64.zip
First bytes: 50 4B 03 04 14 00 02 00
Expected:    bc64eb677027f19e8bade7eeaba9b0b820d524aeec42c7ee92e3fd651ccf3d7a
Actual:      1802eccdc6eed1f1b5b50c59344677394c1b4a0590fe34450909ad13e3823cdd

**Comment by kodybrown** [comment]
Thanks for the report @jmg99 , and thanks for the PR @dragonmaus !
